# This file was generated by GoReleaser. DO NOT EDIT.
class Plsd < Formula
  desc "Develop Elasticsearch painless scripts painlessly"
  homepage "https://github.com/csenol/plsd"
  url "https://github.com/csenol/plsd/releases/download/v0.0.5/plsd_0.0.5_Darwin_x86_64.tar.gz"
  version "0.0.5"
  sha256 "504506d21883bb88549efc141da9d3b58072436643bf42715c03990428a4cefb"

  def install
    bin.install "plsd"
  end
end
