# This file was generated by GoReleaser. DO NOT EDIT.
class Plsd < Formula
  desc "Develop Elasticsearch painless scripts painlessly"
  homepage "https://github.com/csenol/plsd"
  url "https://github.com/csenol/plsd/releases/download/v0.0.4/plsd_0.0.4_Darwin_x86_64.tar.gz"
  version "0.0.4"
  sha256 "670b3530e3f86167c54987c33e4885bb9c65e1c8ce41fc397b40f45fe06dd64b"

  def install
    bin.install "plsd"
  end
end
