# This file was generated by GoReleaser. DO NOT EDIT.
class Plsd < Formula
  desc "Develop Elasticsearch painless scripts painlessly"
  homepage "https://github.com/csenol/plsd"
  url "https://github.com/csenol/plsd/releases/download/v0.0.3/plsd_0.0.3_Darwin_x86_64.tar.gz"
  version "0.0.3"
  sha256 "4bf0ef2f8004ae13a42f5ce69b0a4eb63ec664dde383b5e5a3bc9ce6de6e959a"

  def install
    bin.install "plsd"
  end
end
