# This file was generated by GoReleaser. DO NOT EDIT.
class Plsd < Formula
  desc "Develop Elasticsearch painless scripts painlessly"
  homepage "https://github.com/csenol/plsd"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/csenol/plsd/releases/download/v0.0.6/plsd_0.0.6_Darwin_x86_64.tar.gz"
    sha256 "0daa693bc7c563696f37324e50d3ef396de219bfe90e1aae9565b2f364ac807e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/csenol/plsd/releases/download/v0.0.6/plsd_0.0.6_Linux_x86_64.tar.gz"
      sha256 "811c3548643e1dd209774453098cb73b4742f25aaecdf86f8cb0d289bed01253"
    end
  end

  def install
    bin.install "plsd"
  end
end
